### ISSUE TITLE
Support additional OpenAPI features

### ISSUE THREAD

**Issue by josephbirkner** [Klebert-Engineering/zswag#12]
The zswag-client should support additional OpenApi features to enable more REST-like interfaces:
- [x] #16 Support PUT/DELETE/PATCH __[Released with 0.6.0]__
- [x] #18 Support x-zserio-request-part=* __[Released with 0.6.0]__
- [x] #20 Support parameter schema formats (string/hex/byte/binary)
- [x] #17 Support value array passing schemes
- [x] #19 Support x-zserio-request-part with request field name
- [x] #15 Support path-based argument passing (to support GET)

Comprehensively formulated, this would enable method specs like this:
```yaml
paths:
  <Path>
    [get|put|post|patch|delete]:
       operationId: <Service-Function>
       parameters:
         - in: [query|path]
           name: <Name>
           x-zserio-request-part: <[*|field-name]>
           style: [matrix|form|simple]
           explode: [true|false]
           schema:
             format: [string|byte|hex|binary]
       requestBody:
         content:
           application/x-zserio-object
```

**Comment by erikvdvelden** [comment]
Can you elaborate on "path-based argument passing". Is the idea that if you have a single parameter (like tileID) you could put this in the path? Encoded how?

**Comment by josephbirkner** [comment]
@erikvdvelden exactly, that is the idea. In OpenApi you can specify a method path with an argument like
```yaml
paths:
  /myMethod/{parameter}:
    get:
      in: path
      name: parameter
... 
```
Encoded how is a very good question. The current implementation can only work with a single parameter in base64, but if you could specify e.g. decimal or hex, then something like a single numeric parameter would already be humanly comprehensible, while still directly convertible to a blob.

**Comment by josephbirkner** [comment]
We've had a more in-depth discussion on this. What we are envisioning is to be able to specify path-based arguments in OpenApi with a zserio service schema in the background like this:
```
paths:
  /myMethod/{myParameter}:
    get:
      parameters:
      - in: path
        name: myParameter
        x-zserio-request-part: zserio_request_field
        schema:
          type: string
          format: hex
```
Explanation:
* `x-zserio-request-part` determines the association between a request object and fields from the request object that are placed in the parameter. One may either have a single parameter/body with `x-zserio-request-part=*` to glob the whole blob, or multiple parameters like `x-zserio-request-part=field[.subfield]`, maintaining an excplicit parameterisation of the object.
* The `schema.format` field is a free-form field which OpenApi users/devs are free to fill with custom values. Here we could allow `text/base10/base16/base64` etc. Non-string types would be achieved by changing the `schema.type` to e.g. integer or boolean. Note: Only basic types could be placed this way, lists/structs need blob-style transfer.

Integrating this into the zserio OpenApi client is straight-forward. On the server side not so much, because the generated server WSGI-functions expect a single "blob-to-decode" parameter. But this is assuming the server uses the zserio-generated server stubs. In any other case, the server is free to implement all parameter processing freely as advertised. For example, if the server is a file server, placing tile ids in decimal form into the request URL could be useful?

Thanks for all feedback @erikvdvelden ! @KRE02 I hope I reflected everything correctly.

**Comment by josephbirkner** [comment]
The description of this issue has been updated to reflect additional features as individual issues, including support for the the `x-zserio-request-part` method spec parameter.
